### ISSUE TITLE
Relationship fields aren't rendered correctly

### ISSUE THREAD

**Issue by spekulatius** [eminiarts/nova-tabs#161]
Hello,

I've got tabs with relationships and they seem to not render correctly:

![image](https://user-images.githubusercontent.com/8433587/128048667-51df5983-532d-4005-9171-cacb346c41bd.png)

My code:
```php
                'Content' => [
                    Textarea::make('Text')
                        ->rows(2)
                        ->rules('required'),

                    Markdown::make('Source')
                        ->alwaysShow(),

                    HasMany::make('Images', 'images'),
                ],
```

Versions:

```
laravel/framework                   v8.52.0   The Laravel Framework.
laravel/nova                        3.27.0    A wonderful administration in...
eminiarts/nova-tabs                 1.4.6     Laravel Nova - Tabs.
```

Do I miss something?

Cheers,
Peter

**Comment by RVxLab** [comment]
What happens if you take the `HasMany` out of that tab and put it directly in the `Tabs` array? I'm pretty sure you can't nest a `HasMany` into a tab just like how you can't put a `HasMany` in the same panel as the rest.

As for the search bar being there, that's a new one! It may have to do with the above but I'm not sure, first time I ever see this happen, especially considering that search bar is part of the `HasMany` and not of the tab.

**Comment by spekulatius** [comment]
ah, okay. That makes sense. It does work when moving it out. Thank you for pointing me to this!

**Comment by RVxLab** [comment]
No problem, I'm glad you got it working!
