### ISSUE TITLE
Possible UI Option

### ISSUE THREAD

**Issue by dillingham** [eminiarts/nova-tabs#4]
Nice package, discussions were had here https://github.com/tightenco/nova-package-development/issues/54

Just wanted to drop this layout here incase it's something you'd consider

![option](https://user-images.githubusercontent.com/29180903/50432879-b96a8200-08a2-11e9-947f-994b71df0ef0.png)

**Comment by bajramemini** [comment]
Hello @dillingham 

Thank you for your suggestion.

![image](https://user-images.githubusercontent.com/3426944/50450016-57a22a80-092b-11e9-9c13-91283ea3bbff.png)

This is what I came up with until now. However, I am not sure if it should be in this package. On one hand, it doesn't really matter, if it's Tabs or a Select. On the other hand, this is supposed to be a `nova-tabs` package. At the same time, extracting it to its own package just because of the naming doesn't feel right either.

I might put it in the package. Why not. Or extract it to a new package `relationship-selector` as mentioned in tightenco/nova-package-development#54 

Regards,
Bajram

**Comment by dillingham** [comment]
Hello @bajramemini,
Wow that was fast :) You're right in that it is similar but possibly warrants it's own package.
What do you think about having the dropdown as apart of the section title?

![dropdown](https://user-images.githubusercontent.com/29180903/50450470-4f7ec680-08fc-11e9-8ecb-a01f1d3bc8f3.png)

Sidenote: would be a performance boost if each tab requested it's data on display

**Comment by bajramemini** [comment]
Hello @dillingham 

Yeah, I think you're right. It should be its own package. I am going to extract it to its own package.

I think a dropdown arrow is nice, maybe this can be optional.

And yes, loading the component on display would be a performance boost. I think, if you have 3 or 4 Tabs, it's ok to load everything up front. But if you have a lot of Relations, that's definitely going to be an issue.

**Comment by dillingham** [comment]
Hello @bajramemini,

That is wonderful, look forward to using it myself. 

With the dropdown arrow it may remove the need for a white background on the toolbar.
![no-background](https://user-images.githubusercontent.com/29180903/50450783-0af42a80-08fe-11e9-8d41-4b658b1c1f83.png)

Agreed, 3-4 tabs is no problem. I think if this package had the request on tab selection it could very well be the preferred suggestion for anyone experiencing performance issues with many relationships.

**Comment by dillingham** [comment]
Another option, further reduced. Kind of my favorite :)

![cleaner](https://user-images.githubusercontent.com/29180903/50453643-1f412300-0910-11e9-80e2-b51cdde3b17c.png)

**Comment by bajramemini** [comment]
Hello @dillingham 

Here you go:
https://github.com/eminiarts/nova-relationship-selector

Will close this issue.

If you have further questions, let me know.

Regards,
Bajram

**Comment by dillingham** [comment]
@bajramemini you are awesome!
