### ISSUE TITLE
BelongsToMany causes "Trying to get property 'resourceClass' of non-object"

### ISSUE THREAD

**Issue by cliffordjames** [eminiarts/nova-tabs#6]
```php
public function fields(Request $request)
{
    return [
        //...

        Tabs::make('Relations')
            ->addTab(
                __('Ssl Certificates'),
                BelongsToMany::make('Ssl Certificates', 'ssl_certificates', SslCertificate::class)
                    ->searchable()
            )
            //...
    ];
}
```

Causes "Trying to get property 'resourceClass' of non-object" exception when trying to attach a Ssl Certificate, but when I move the BelongsToMany outside of the Tab everything works:

```php
public function fields(Request $request)
{
    return [
        //...

         Tabs::make('Relations')
            //...

         BelongsToMany::make('Ssl Certificates', 'ssl_certificates', SslCertificate::class)
            ->searchable()
    ];
}
```

**Comment by avs262** [comment]
+1

**Comment by bajramemini** [comment]
Thanks for the issue.

Will have a look at it tomorrow.

Regards

**Comment by authanram** [comment]
I can confirm this.

```php
// Working
BelongsToMany::make('Users')
,

// Not working
Tabs::make('Relations')
    ->addTab(__('Users'), BelongsToMany::make('Users'))
    ->exceptOnForms()
,
```

Trying to get property of non-object {"userId":1,"email":"***","exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at vendor/laravel/nova/src/Http/Controllers/AttachableController.php:23)

Line vendor/laravel/nova/src/Http/Controllers/AttachableController.php:22-24
```php
$withTrashed = $this->shouldIncludeTrashed(
    $request, $associatedResource = $field->resourceClass
);
```

**Comment by bajramemini** [comment]
This is very strange. I am using it in one application and everything works fine.

On another, it doesn't work as expected, but it doesn't fail either.

It should be "attach" Role instead of "create".

![image](https://user-images.githubusercontent.com/3426944/50840519-fcc4f600-1362-11e9-9d71-7c14b8896b58.png)

@authanram, @avs262  or @cliffordjames could you provide me with a Model, Migration and a Nova-Resource where it doesn't work at all? Somehow, I can not reproduce this issue.

**Comment by bajramemini** [comment]
Ok, found an error when having SoftDeletes and visiting `nova-api/{resource}/{resource_id}/attachable/{field}?search=&withTrashed=false`.

Will try to solve it asap.

**Comment by authanram** [comment]
> Ok, found an error when having SoftDeletes and visiting `nova-api/{resource}/{resource_id}/attachable/{field}?search=&withTrashed=false`.
> 
> Will try to solve it asap.

I just read the notification mail from github and realized i forgot to say, the issue happens on the action to attach another model. sorry for that. hope you haven't spent that much time.

**Comment by bajramemini** [comment]
Ok, I managed to fix it.


Make sure to use the `AvailableTabFields` Trait in your Nova Resource.

```php
// in app/Nova/Resource.php

use Eminiarts\Tabs\Tabs;
use Eminiarts\Tabs\AvailableTabFields;

class User extends Resource
{
        
    use AvailableTabFields;

    public function fields(Request $request)
    {
        return [
            
            // ...
            
            Tabs::make('Relations')
                ->addTab(__('Invoices'), HasMany::make('Invoices'))
                ->addTab(__('Notes'), HasMany::make('Notes'))
                ->addTab(__('Roles'), BelongsToMany::make('Roles'))
            ,

            // ...
            
        ];
    }

}
```

Since Nova is asking for the Fields in different parts of each application, I rewrote some logic so Nova could find each Field, independent whether it is in Tabs or not. 

- Added Trait to Support available Fields within Tabs
- Removed the Controller and App Binding
- [Tagged new Release](https://github.com/eminiarts/nova-tabs/releases/tag/0.2.0)

Let me know if you still have problems.

Regards
Bajram

**Comment by cliffordjames** [comment]
@bajramemini Works! Thanks!
